services:
  odoo:
    image: odoo:17.0
    container_name: odoo-app
    env_file: 
      - .env
    ports:
      - "8069:8069"
    depends_on:
      - odoo-postgres
    volumes:
      - ./etc/odoo:/etc/odoo  
      - ./addons:/mnt/extra-addons # untuk menyimpan custom module
      - ./var/lib/odoo:/var/lib/odoo # menyimpan data-data dari odoo tapi bukan database
    networks:
      - odoo-network
  odoo-postgres:
    image: postgres:16.1 
    container_name: odoo-db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge
